# Generated by Django 4.2.4 on 2023-08-09 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('sleep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='api.sleep')),
            ],
        ),
        migrations.CreateModel(
            name='MoodChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=64)),
                ('mood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='api.mood')),
            ],
        ),
        migrations.CreateModel(
            name='DigestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=64)),
                ('digestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='api.digestion')),
            ],
        ),
    ]
